name: ExpenseTracker CI Build

on:
  push: 
   branches: [main]
   paths-ignore:
     - '**/*.md'
     - '**/*.gitignore'
     - '**/*.gitattributes'
  workflow_dispatch:
permissions: 
  contents: read
jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources
          
      - name: Restore Dependencies
        run: dotnet restore 
        
      - name: Decode Android keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > myapp.keystore
          
      - name: Publish MAUI Android
        run: dotnet publish -f:net10.0-android -c:Release /p:AndroidSigningKeyPass=${{secrets.keystorepassword}} /p:AndroidSigningStorePass=${{secrets.keystorepassword}}

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: '**/bin/Release/net10.0-android/publish/*.apk'
